version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ANSKk08aPEDbFjDO
    volumes:
      - ./data:/var/lib/mysql
      - ./bak:/bak
    restart: always
